### ISSUE TITLE
 Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by alarsalars** [clarity20/bash2py#35]
I have downloaded different version so far, all give the same error.
I feel I a missing some of the pre-requests to run this tool.
I followed those steps:
1. I download the .zip file
2. I unzip it.
3. I move inside the bash-4.3.30 and run this command "chmod +x configure"
4. I go back one step to the directory where the installation file is located, and I run "./install"
5. Then it shows that the bash2pyengine is moved to ~bin
6. then I put one file with .sh extension in the same bin file where the bash2pyengine is located, and I run "./bash2pyengine -f main.sh". The command "./bash2py -f main.sh" is not working because the bash2py is not a command.
7. it always shows the same error, which is "Segmentation fault (core dumped)"
8. The main.sh.py file is created, but it is always empty.

Any suggestion what I am doing wrong?????

**Comment by clarity20** [comment]
Seg faults are bad in general. Instead of crashing, `bash2pyengine` should really handle your use case gracefully. (It's a pretty routine fix; I'll put that on the agenda for when I can return to active development.) Thank you for pointing out this behavior. 

That said, if you check the README carefully you'll see the `-f` option doesn't apply to `bash2pyengine`, so just run it with `bash2pyengine main.sh` instead. Also, in order to run `bash2py` you need to set execute permissions just like you did for `configure` in your step (3), so give that a try too. Let me know how these tips work for you.

**Comment by alarsalars** [comment]
Thank you for your reply, actually, I was able to run it but only with
basic main file with few echo commands. As I understand, it does not
support few commands I have in my main.sh file, therefore, it raises error.
I am attaching my main.sh file in case you want to give it a try.

Thank you and best regards
Taha

Am Fr., 20. Okt. 2023 um 07:24 Uhr schrieb Michael Wood <
***@***.***>:

**Comment by clarity20** [comment]
I'm not getting a segfault when I run `bash2pyengine -f nested_fns.sh`. (That's a test case I added to `tests/v4_tests`.) Instead, I get a python script that produces the same printout as the original bash script.

I just noticed you said you downloaded a different version of `bash2py`. Can you download **this** version and install and run it? I've put some logging in place so you should see some screen output, essentially an abbreviated trace of the program flow. If the crash persists you can open another ticket and provide a copy of your input file (`main.sh` or whatever else). In the meantime, I'm going to classify the reported issue as not being an issue with this version, _per se_.
