### ISSUE TITLE
xmalloc leads to segmentation faults

### ISSUE THREAD

**Issue by tomasohara** [clarity20/bash2py#5]
The use of xmalloc is leading to segmentation faults, a known issue for more recent version of University of Waterloo's source (e.g., 3.0 and after).

Version 2.3 of Bash2Py works fine, as noted [here](https://unix.stackexchange.com/questions/627842/problem-when-converting-bash-to-python-using-bash2py). Following this lead, I tracked down the issue to the use of xmalloc, which were added in later versions.

A workaround for this is to map the xmalloc calls into regular malloc.

```
$ cat disable_xmalloc.h
#if !defined (_DISABLE_XMALLOC_H_)
#  define _DISABLE_XMALLOC_H_

#  ifdef BASH2PY

#    if 1	/* disable xmalloc since bug in burp.c usage */

#      include "stdc.h"
#      include "bashansi.h"

#      define xmalloc malloc
#      define xrealloc realloc
#      define xfree free

#  endif /* disable */

# endif /* BASH2PY */

#endif	/* _DISABLE_XMALLOC_H_ */


$ grep -c disable_xmalloc.h *.[cyh] | grep -v :0 | tr -d :1
burp.c
copy_cmd.c
eval.c
make_cmd.c
print_cmd.c
translate.c
translate_expr.c
```

I tested this over the 400+ scripts in the bash test, and 300+ now can be translated without segmentation faults. (Previously, running the code over just about any input would abort.)

Other modules have Bash2Py customizations, so disabling xmalloc in these should resolve the remaining sources of the segmentation faults. I tried disabling it globally, but ran into compilation issues.

**Comment by gokaybiz** [comment]
Hey! Can you make a pr for solution?

**Comment by clarity20** [comment]
Thanks for your research. A nice fix for "xmalloc" would be much appreciated.

**Comment by tomasohara** [comment]
I had problems trying to come up with a way to disable xmalloc throughout the bash code base. A complication is that there are three different implementations in the source.

Therefore, I submitted a query to the Bash mailing list to see if they have any tips:
  https://lists.gnu.org/archive/html/help-bash/2023-07/msg00008.html

Best,
Tom

**Comment by clarity20** [comment]
Hi Tom,

I can see that replacing `xmalloc` with `malloc` in one key place helps a little bit. Then if I implement your general-purpose workaround, I get the same overall improvement with the test cases as you describe.

I like it that with your workaround, the immediate code changes are localized and we can be agnostic about `malloc` and `xmalloc` going forward (because we respect the `#ifdef BASH2PY` guards).

In a perfect world we would refactor `bash2py` out of `bash` entirely and then change everything here to vanilla malloc/realloc. Thoughts come to mind about a God-object with function pointers into `bash` and into itself as needed. But their `main()` is buried deep inside `shell.c` so things would get messy fast.

**Comment by tomasohara** [comment]
You're welcome. I was that the main code being named "burp" is telling!
